---
- hosts: manager_group worker_group
  become: true
  roles:
  - initial-setup
  - docker-install

- hosts: manager_group
  become: true
  roles:
  - swarm-init

- hosts: worker_group
  become: true
  roles:
  - swarm-join

- hosts: manager_group
  become: true
  roles:
  - clone-repo
  - swarm-stack

- host: load_balancer
  become: true
  roles:
  - load-balancer