---
- hosts: manager-group worker-group
  become: true
  roles:
  - initial-setup
  - docker-install

- hosts: manager-group
  become: true
  roles:
  - swarm-init

- hosts: worker-group
  become: true
  roles:
  - swarm-join

- hosts: manager-group
  become: true
  roles:
  - clone-repo
  - swarm-stack
