---
- name: "Build Docker Images"
  shell: | 
    cd app && cd project && docker-compose build 

- name: "Push Images to Dockerhub"
  shell: |
   docker push ahsansabir3/s1:latest
   docker push ahsansabir3/s2:latest
   docker push ahsansabir3/s3:latest
   docker push ahsansabir3/s4:latest