---
- name: "Build Docker Images"
  shell: | 
    cd app && cd project && docker-compose build 

- name: "Push Images to Dockerhub"
  shell: |
    docker login
    docker push ahsansabir30/s1:latest
    docker push ahsansabir30/s2:latest
    docker push ahsansabir30/s3:latest
    docker push ahsansabir30/s4:latest