---
- name: "Build Docker Images"
  shell: | 
    cd app && cd project && docker-compose build

- name: "Log into DockerHub"
  docker_login:
    username: "{{ lookup('env', 'USERNAME') }}"
    password: "{{ lookup('env', 'PASSWORD') }}" 

- name: "Push Image to Dockerhub"
  command: docker push docker.io/ahsansabir/s1:latest
