---
- name: "Build Docker Images"
  shell: | 
    cd app && cd project && docker-compose build

- name: Log out of DockerHub
  docker_login:
    state: absent

- name: "Push Images to DockerHub"
  shell: |
    cd app && cd project && docker login --username "{{ lookup('env', 'USERNAME') }}" --password-stdin < "{{ lookup('env', 'PASSWORD') }}"  && docker-compose push