---
- name: "Build Docker Images"
  shell: | 
    cd app && cd project && docker-compose build

- name: "Push Images to DockerHub"
  shell: | 
    sudo chmod +r ~/password.txt 
    docker login --username "{{ lookup('env', 'username') }}" --password-stdin < ~/password.txt
    cd app && cd project && docker-compose push
