---
- name: "Build Docker Images"
  shell: | 
    cd app && cd project && docker-compose build 

- name: "Push Docker Images"
  shell: |
    docker push ahsansabir/s1 
    docker push ahsansabir/s2
    docker push ahsansabir/s3
    docker push ahsansabir/s4