---
- name: "Build Docker Images"
  shell: | 
    cd app && cd project && docker-compose build

- name: "Push Images to DockerHub"
  command: docker login --username "{{ lookup('env', 'USERNAME') }}" --password "{{ lookup('env', 'PASSWORD') }}" && docker push ahsansabir/s1:latest
