---
- name: "Build Docker Images"
  shell: | 
    cd app && cd project && docker-compose build

- name: Log out of DockerHub
  docker_login:
    state: absent

- name: "Log into DockerHub"
  docker_login:
    username: "{{ lookup('env', 'USERNAME') }}"
    password: "{{ lookup('env', 'PASSWORD') }}" 
    email: "{{ lookup('env', 'EMAIL') }}" 

- name: "Push S1 to Dockerhub"
  docker_image:
    name: ahsansabir30/s1:latest
    repository: docker.io:ahsansabir30/s1:latest
    push: yes
    source: local