---
- name: "Build Docker Images"
  shell: | 
    cd app && cd project && docker-compose build

- name: "Login into DockerHub"
  docker_login:
    username: "{{ lookup('env', 'USERNAME') }}"
    password: "{{ lookup('env', 'PASSWORD') }}"

- name: "Push Images to DockerHub"
  shell: |
    cd app && cd project && docker login -u="{{ lookup('env', 'USERNAME') }}" -p="{{ lookup('env', 'PASSWORD') }}" && docker-compose push