---
- name: "Build Docker Images"
  shell: | 
    cd app && cd project && docker-compose build

- name: "Push Images to DockerHub"
  shell: | 
    docker login --username foo --password-stdin < ~/my_password.txt 
    cd app && cd project && docker-compose push
