---
- name: "Install packages for stack deployment"
  pip:
    name:
    - jsondiff
    - pyyaml

- name: "Deploy stack using docker compose file"
  docker_stack:
    state: present
    name: mystack
    compose:
    - /home/jenkins/SFIA2/docker-compose.yaml