---
- name: "Install packages for stack deployment"
  pip:
    name:
    - jsondiff
    - pyyaml

- name: "Deploy stack using docker compose file"
  docker_stack:
    state: present
    name: mystack
    compose:
    - /home/jenkins/app/project/docker-compose.yaml

- name: Prune everything
  docker_prune:
    containers: true
    images: true
    networks: true
    builder_cache: true